name: Build and Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        name: Build and Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 'latest'

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            - name: Create extension zip
              run: |
                  cd dist
                  zip -r ../tsukuyomi-extension.zip .
                  cd ..

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: tsukuyomi-extension.zip
                  generate_release_notes: true
